#!/bin/sh

tty=tty6
TERM_NAME=linux
BAUD_RATE=38400

[ -r conf ] && . ./conf

if [ -x /sbin/getty -o -x /bin/getty ]; then
	# busybox
	GETTY=getty
elif [ -x /sbin/agetty -o -x /bin/agetty ]; then
	# util-linux
	GETTY=agetty
fi

exec setsid ${GETTY} ${GETTY_ARGS} \
	"${tty}" "${BAUD_RATE}" "${TERM_NAME}"
